name: Release

on:
  push:
    branches: 
      - main
      - beta
  pull_request:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Release
      uses: ./.github/workflows/prerelease
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release