name: Release

on:
  push:
    branches: 
      - main
      - beta

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Prerelease
      uses: ./.github/workflows/prerelease
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release